import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

import { Hero, Layout, OperatingHours } from '~/components'
import { API } from '~/constants'
import {
    BarbersResponse,
    HeroResponse,
    HomePageRequest,
    OperatingHoursResponse,
    SiteSettingsResponse,
} from '~/types'
import { callApi } from '~/utils'

type Props = {
    data: {
        barber: BarbersResponse['data']
        hero: HeroResponse['data']['attributes']
        siteSettings: SiteSettingsResponse['data']['attributes']
        operatingHours: OperatingHoursResponse['data']['attributes']['time_slot']
    }
    preview: boolean
}

const Home: NextPage<Props> = ({ data, preview }) => {
    const { barber, hero, siteSettings, operatingHours } = data

    return (
        <>
            <Head>
                <title>{siteSettings.business_name}</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <Layout preview={preview} siteSettings={siteSettings}>
                    <Hero attributes={hero} />
                    {barber.map(({ attributes, id }) => (
                        <div key={id}>
                            <Image
                                src={`${API.strapiBase}${attributes.photo.data.attributes.url}`}
                                alt={attributes.name}
                                width={200}
                                height={200}
                            />
                            <h2>{attributes.name}</h2>
                            <p>{attributes.bio}</p>
                        </div>
                    ))}
                    <OperatingHours operatingHours={operatingHours} />
                </Layout>
            </main>
        </>
    )
}

export default Home

export const getStaticProps: GetStaticProps = async ({ preview }) => {
    const siteSettings = await callApi<SiteSettingsResponse>(
        `${API.strapi}/site-setting?populate=*`,
        {},
        preview,
    )

    const operatingHours = await callApi<OperatingHoursResponse>(
        `${API.strapi}/business-hour?populate=*`,
        {},
        preview,
    )
    const homePage = await callApi<HomePageRequest>(
        `${API.strapi}/home?populate=*`,
        {},
        preview,
    )
    const heroId = homePage?.data.attributes.hero.data.id

    const hero = await callApi<HeroResponse>(
        `${API.strapi}/heroes/${heroId}?populate=*`,
        {},
        preview,
    )
    const barber = await callApi<BarbersResponse>(
        `${API.strapi}/barbers?populate=*`,
        {},
        preview,
    )

    return {
        props: {
            data: {
                siteSettings: siteSettings?.data.attributes ?? [],
                operatingHours: operatingHours?.data.attributes.time_slot ?? [],
                barber: barber?.data ?? [],
                hero: hero?.data.attributes ?? [],
            },
            preview: !!preview,
        },
    }
}
