import type { NextPage } from 'next'
import Head from 'next/head'

import { Layout, Login } from '~/components'

const Admin: NextPage = () => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <Layout>
                    <Login />
                </Layout>
            </main>
        </>
    )
}

export default Admin
